services:
  accounts:
    image: "kddhan/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazyBank

  loans:
    image: "kddhan/loans:s4"
    container_name: loans-ms
    ports:
      - "8091:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazyBank

  cards:
    image: "kddhan/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazyBank
networks:
  eazyBank:
    driver: "bridge"